version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.yml:/etc/grafana/grafana.yml
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus-storage:
  grafana-storage:
